services :
    eureka-server:
        build : ./Service_Registry
        image : eureka-server
        ports :
            - "8761:8761"
        networks:
            - ecommerce-network
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
            interval: 30s
            timeout: 10s
            retries: 10
            start_period: 20s
            

    api-gateway:
        build : ./GateWay
        image : api-gateway
        ports :
            - "8080:8080"
        environment:
            - EUREKA_SERVER=http://eureka-server:8761/eureka/
        networks:
            - ecommerce-network
        depends_on:
            eureka-server:
                condition: service_healthy


    product-service:
        build : ./Product-Service
        image : product-service
        ports :
            - "8081:8080"
        environment:
            - EUREKA_SERVER=http://eureka-server:8761/eureka/
        networks:
            - ecommerce-network
        depends_on:
            eureka-server:
                condition: service_healthy
    user-service:
        build : ./UserService
        image : user-service
        ports :
            - "8087:8080"
        environment:    
            - EUREKA_SERVER=http://eureka-server:8761/eureka/
        networks:
            - ecommerce-network
        depends_on:
            eureka-server:
                condition: service_healthy
    order-service:
        build : ./OrderService
        image : order-service
        ports :
            - "8082:8080"
        environment:    
            - EUREKA_SERVER=http://eureka-server:8761/eureka/
        networks:
            - ecommerce-network
        depends_on:
            eureka-server:
                condition: service_healthy
        
    cart-service:
        build : ./CartService
        image : cart-service
        ports :
            - "8083:8080"
        environment:    
            - EUREKA_SERVER=http://eureka-server:8761/eureka/
        networks:
            - ecommerce-network
        depends_on:
            eureka-server:
                condition: service_healthy
    payment-service:
        build : ./PaymentService
        image : payment-service
        ports :
            - "8084:8080"
        environment:    
            - EUREKA_SERVER=http://eureka-server:8761/eureka/
        networks:
            - ecommerce-network
        depends_on:
            eureka-server:
                condition: service_healthy
    inventory-service:
        build : ./InventoryService
        image : inventory-service
        ports :
            - "8085:8080"
        environment:    
            - EUREKA_SERVER=http://eureka-server:8761/eureka/
        networks:
            - ecommerce-network
        depends_on:
            eureka-server:
                condition: service_healthy
    notification-service:
        build : ./NotificationService
        image : notification-service
        ports :
            - "8086:8080"
        environment:    
            - EUREKA_SERVER=http://eureka-server:8761/eureka/
        networks:
            - ecommerce-network
        depends_on:
            eureka-server:
                condition: service_healthy

networks:
    ecommerce-network:
        driver: bridge
