spring.application.name=GateWay

server.port=8080

#routes 1

spring.cloud.gateway.routes[0].id=UserService
spring.cloud.gateway.routes[0].uri=lb://USERSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/user/**

#routes 2

spring.cloud.gateway.routes[1].id=OrderService
spring.cloud.gateway.routes[1].uri=lb://ORDERSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/order/**

#routes 3

spring.cloud.gateway.routes[2].id=Product-Service
spring.cloud.gateway.routes[2].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/products/**

#routes 4

spring.cloud.gateway.routes[3].id=cart-service
spring.cloud.gateway.routes[3].uri=lb://CART-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/cart/**

#routes 5

spring.cloud.gateway.routes[4].id=notification-service
spring.cloud.gateway.routes[4].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/notifications/**

#routes 6

spring.cloud.gateway.routes[5].id=payment-service
spring.cloud.gateway.routes[5].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/wallets/**

#routes 7

spring.cloud.gateway.routes[6].id=inventory-service
spring.cloud.gateway.routes[6].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/stocks/**

# Payment APIs
spring.cloud.gateway.routes[7].id=payment-route
spring.cloud.gateway.routes[7].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/payments/**
eureka.client.service-url.defaultZone=${EUREKA_SERVER:http://localhost:8761/eureka/}

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true