spring.application.name=GateWay

server.port=8080

#routes 1

spring.cloud.gateway.routes[0].id=UserService
spring.cloud.gateway.routes[0].uri=lb://UserService
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/user**

#routes 2

spring.cloud.gateway.routes[1].id=OrderService
spring.cloud.gateway.routes[1].uri=lb://OrderService
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/order/**

#routes 3

spring.cloud.gateway.routes[2].id=Product-Service
spring.cloud.gateway.routes[2].uri=lb://Product-Service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/products/**

#routes 4

spring.cloud.gateway.routes[3].id=cart-service
spring.cloud.gateway.routes[3].uri=lb://cart-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/cart/**

#routes 5

spring.cloud.gateway.routes[4].id=notification-service
spring.cloud.gateway.routes[4].uri=lb://NotificationService
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/notifications/**

#routes 6

spring.cloud.gateway.routes[5].id=payment-service
spring.cloud.gateway.routes[5].uri=lb://PaymentService
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/wallets/**

#routes 7

spring.cloud.gateway.routes[6].id=inventory-service
spring.cloud.gateway.routes[6].uri=lb://InventoryService
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/stocks/**

# Payment APIs
spring.cloud.gateway.routes[7].id=payment-route
spring.cloud.gateway.routes[7].uri=lb://PaymentService
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/payments/**