spring.application.name=OrderService

# PostgreSQL

spring.datasource.url=jdbc:postgresql://e-commerce-njha5901-604a.l.aivencloud.com:16263/order-db?sslmode=require

spring.datasource.username=avnadmin
spring.datasource.password=AVNS_I1trTeatLGFThkQ3_OJ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true