spring.application.name=cart-service
server.port=0
# Data Base Configuration
spring.datasource.url=jdbc:postgresql://e-commerce-njha5901-604a.l.aivencloud.com:16263/cart-db?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_I1trTeatLGFThkQ3_OJ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

#Kafka Setup 

spring.kafka.bootstrap-servers=e-commerce-kafka-njha5901-604a.g.aivencloud.com:16265
spring.kafka.client-id=order-service

# SSL
spring.kafka.properties.security.protocol=SSL

spring.kafka.properties.ssl.keystore.type=PKCS12
spring.kafka.properties.ssl.keystore.location=src/main/resources/certs/client.keystore.p12
spring.kafka.properties.ssl.keystore.password=changeit
spring.kafka.properties.ssl.key.password=changeit

spring.kafka.properties.ssl.truststore.type=JKS
spring.kafka.properties.ssl.truststore.location=src/main/resources/certs/client.truststore.jks
spring.kafka.properties.ssl.truststore.password=changeit